const url = {
  test: "/test",
  loadSensorData: "/load-sensor-data",
  login: "/login",
  tokenIssuance: "/token-v1",
  operateSimpleActuator: "/operate-actuator/simple",
  operateNutrientActuator: "/operate-actuator/nutrient",
  operateNutrientStop: "/operate-actuator/nutrient-stop",
  emergency: "/emergency",
  loadActuatorRecord: "/load-actuator-record",
  minutes: "/load-sensor-data/minutes",
  hours: "/load-sensor-data/hours",
  days: "/load-sensor-data/days",
  months: "/load-sensor-data/months",
  years: "/load-sensor-data/years",
  mainInside: "/load-sensor-data/main-inside",
  mainOutside: "/load-sensor-data/main-outside",
  update: "/update",
  loadNutrientData: "/operate-actuator/load-nutrient-data",
  bedData: "/load-sensor-data/bed-data",
  start: "/operate-actuator/start",
  stop: "/operate-actuator/stop",
  nutricultureMachineStatus: "/operate-actuator/nutriculture-machine-status",
  easySelection: "/operate-actuator/control-mode-easy",
  detailSelection: "/operate-actuator/control-mode-detail",
  easySetting: "/operate-actuator/easy-setting",
  detailSettingTime: "/operate-actuator/detail-setting-time",
  detailSettingMatter: "/operate-actuator/detail-setting-matter",
  detailSettingIsUse: "/operate-actuator/detail-setting-is-use",
  detailSettingTrayIsUse: "/operate-actuator/detail-setting-tray-is-use",
  hourConsumptionData: "/load-sensor-data/hour-consum",
  dayConsumptionData: "/load-sensor-data/day-consum",
  monthConsumptionData: "/load-sensor-data/month-consum",
  yearConsumptionData: "/load-sensor-data/year-consum",
};

module.exports = url;
